## 03. 텐서 조작하기(Tensor Manipulation)2 

#### 5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경 (매우 중요)
파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할.  
Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할을 함.  

In [2]:
import numpy as np
import torch

In [3]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

ft라는 이름의 3차원 텐서를 만들었음.  
크기(shape)를 확인해보자.

In [4]:
print(ft.shape)

torch.Size([2, 2, 3])


#### 5-1) 3차원 텐서에서 2차원 텐서로 변경

이제 ft 텐서를 view를 사용하여 크기(shape)를 2차원 텐서로 변경해보자.

In [5]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


view([-1, 3])이 가지는 의미  
-> -1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에게 맡기겠다는 의미  
-> 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미  
-> 다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되, (?, 3)의 크기로 변경하라는 의미입니다. 결과적으로 (4, 3)의 크기를 가지는 텐서를 얻었음.

내부적으로 크기 변환은 (2, 2, 3) -> (2 X 2, 3) -> (4, 3) 으로 이루어졌음  

규칙을 정리해보자.
- view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소 개수가 유지되어야 함.
- 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추

#### 5-2) 3차원 텐서의 크기 변경
이번에는 3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기(shape)를 바꾸는 작업을 해보자.  
view로 텐서의 크기를 변경하더라도 원소의 수는 유지되어야함.  
그렇다면 (2 x 2 x 3)텐서를 (? x 1 x 3) 텐서로 변경하라고 하면 ?는 몇 차원일까?

In [6]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#### 6) 스퀴즈(Squeeze) - 1인 차원을 제거한다. 
스퀴즈는 차원이 1인 경우 해당 차원을 제거.

In [7]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [8]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


위의 결과는 1이었던 두번째 차원이 제거되면서 (3,)의 크기를 가지는 텐서로 변경되어 1차원 벡터가 된 것을 보여줌

#### 7) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다. 
언스퀴즈는 스퀴즈와 정반대.  
특정 위치에 1인 차원을 추가할 수 있음

In [9]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


현재는 차원이 1개인 1차원 벡터.  
여기에 첫번재 차원에 1인 차원을 추가해보자.  
첫번째 차원의 인덱스를 의미하는 숫자 0을 인자로 넣으면 첫번째 차원에 1인 차원이 추가됨.

In [11]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번재 차원을 의미
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


방금 한 연산을 앞서 배운 view로도 구현 가능.  
2차원으로 바꾸고 싶으면서 첫번재 차원은 1이기를 원한다면 view에서 (1, -1)을 인자로 사용하면 됨.

In [12]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


이번에는 unsqueeze의 인자로 1을 넣어보자.  인덱스틑 0부터 시작하므로 이는 두번째 차원에 1을 추가하겠다는 의미.  
현재 크기는 (3,)이었으므로 두번째 차원에 1차원을 추가하면 (3, 1)의 크기를 가지게 됨

In [14]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


- view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절해준다!

#### 8) 타입 캐스팅(Type Casting)
텐서에는 자료형이 있음.  
각 데이터형별로 정의되어 있는데, 예를 들어 32비트의 유동 소수점은 torch.FloatTensor, 64비트의 부호 있는 정수는 torch.LongTensor를 사용.  
GPU연산을 위한 자료형도 있음. -> e.g) torch.cuda.FloatTensor

그리고 이 자료형을 변환하는 것을 **타입 캐스팅** 이라고 함.

In [15]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


텐서에다가 .float()를 붙이면 float형으로 변환 가능

In [16]:
print(lt.float())

tensor([1., 2., 3., 4.])


이번에는 Byte 타입의 bt라는 텐서를 만들어보자.

In [19]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


여기에 .long()이라고 하면 long 타입 텐서로, .float()라고 하면 float 타입 텐서로 변경됨

In [20]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


#### 9) 연결하기 (concatenate)
이번에는 두 텐서를 연결하는 방법에 대해 알아보자. 


In [21]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

이제 두 텐서를 torch.cat([ ])를 통해 연결해보자.  
그런데 연결 방법은 한가지만 있는 것이 아님!  
torch.cat은 어느 차원을 늘릴지 인자로 줄 수 있음.  
예를 들어 dim = 0은 첫번째 차원을 늘리라는 의미를 담고 있음.

In [23]:
print(torch.cat([x, y], dim = 0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [25]:
print(torch.cat([x, y], dim = 1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


- 딥러닝에서는 주로 모델의 입력 또는 중간 연산에서 두 개의 텐서를 연결하는 경우가 많음. 두 텐서를 연결해서 입력으로 사용하는 것은 두 가지의 정보를 모두 사용한다는 의미를 가지고 있음.

#### 10) 스택킹 (Stacking)
연결(concatenate)을 하는 또 다른 방법으로는 스택킹(Stacking)이 있음.  
이는 영어로 쌓는다는 의미로, 때로는 연결을 하는 것보다 스택킹이 더 편리할 때가 있는데, 스택킹이 더 많은 연산을 포함하고 있기 때문!

In [26]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

이제 torch.stack을 통해 3개의 벡터를 모두 스택킹해보자.

In [27]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


위 결과는 3개의 벡터가 순차적으로 쌓여 (3 x 2) 텐서가 된 것을 보여줌.  
스택킹은 사실 많으 연산을 한 번에 축약하고 있음.  
예를 들어 위 작업은 아래의 코드와 동일한 작업임.  
-> x, y, z는 기존에 전부 (2,)의 크기를 가졌음. 그런데, .unsqueeze(0)을 하므로서 3개의 벡터는 전부 (1, 2)의 크기의 2차원 텐서로 변경됨. 여기에 연결(concatenate)을 의미하는 cat을 사용하면 (3 X 2) 텐서가 됨

In [28]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


위에서는 torch.stack([x, y, z])라는 한 번의 명령어로 수행했지만, concatenate로 이를 구현하려 했더니 꽤 복잡해짐.  

스택킹에 추가적으로 dim을 인자로 줄 수도 있음.  
이는 두 번째 차원이 증가하도록 쌓으라는 의미로 해석할 수 있음

In [29]:
print(torch.stack([x, y, z], dim = 1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [34]:
print(torch.cat([x, y, z]))

tensor([1., 4., 2., 5., 3., 6.])


#### 11) ones_like와 zeros_like - 0으로 채워진 탠서와 1로 채워진 텐서

In [35]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


위 텐서에 ones_like를 하면 동일한 크기(shape)지만 1으로만 값이 채워진 텐서를 생성한다.

In [36]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


위 텐서에 zeros_like를 하면 동일한 크기(shape)지만 0으로 값이 채워진 텐서를 생성한다.

In [38]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### 12) In-place Operation (덮어쓰기 연산)

In [39]:
x = torch.FloatTensor([[1, 2], [3, 4]])

곱하기 연산을 한 값과 기존의 값을 출력해보자.

In [40]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


첫번째 출력은 곱하기 2가 수행된 결과를 보여주고, 두번째 출력은 기존의 값이 그대로 출력된 것을 확인할 수 있음.  
곱하기 2를 수행했지만 이를 x에다가 다시 저장하지 않았기 때문.  

그런데 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 함!

In [41]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
